### PR TITLE
Update parser to support TypeScript v3.4.5

### PR DESCRIPTION
**Pull request by draaglom**
PS: thanks for making Madge!

### CODE REVIEW

**Comment by anion155** [comment]
@pahen ping

**Comment by pahen** [comment]
Thanks! I see that version `typescript-estree` 1.9.0 is released now. Maybe we should update to that before merging?

**Comment by fatso83** [comment]
That's #18 :-)

**Comment by fatso83** [comment]
I could really need this to avoid https://github.com/Microsoft/TypeScript/issues/30077, which is currently making our builds fail.

**Comment by anion155** [comment]
@fatso83 for temp fix you could just use `npm i -D typescript@latest @typescript-eslint/typescript-estree@latest`. Worked for me

**Pull request closed without merging**
