### PR TITLE
Add support for runtime dynamic imports

### PR DESCRIPTION
**Pull request by maleetz**
Thanks for the great package! I'm using this via dependency-tree and would like to include dependencies that are imported at runtime. Since it's a bigger change I decided to make it optional but could go either way on that. Happy to make any requested changes. Thanks!

### CODE REVIEW

**Comment by pahen** [comment]
Sorry for being negative but this only solves a small part of the problem and supporting this is much more complicated. Doing this using static analysis is not a good idea and would never work in a satisfying way. So if we can't support this 100% I would rather not support it at all. But thanks for your effort!

**Comment by maleetz** [comment]
@pahen Thanks for the feedback. Could you give me an example of what is left to solve for supporting runtime dynamic imports? I would love to understand more what you were thinking.

**Comment by pahen** [comment]
I'll take a second look at this

**Comment by pahen** [comment]
This was fixed in https://github.com/pahen/detective-typescript/commit/5977a3932d7e8a7168c9a3a4b0ab0c5334d9a9ee and published to NPM as v7.0.0

**Comment by pahen** [comment]
Using same approach as https://github.com/dependents/node-detective-es6

**Comment by maleetz** [comment]
Awesome, thanks! I agree this is a nicer API. Hopefully no big impacts with the default for skipAsyncImports being false.

**Pull request closed without merging**
