### PR TITLE
Require Node.js 10 and upgrade @typescript-eslint/typescript-estree

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by pahen** [comment]
I'm not using TypeScript myself. Is v4 backwards compatible?

**Comment by realityking** [comment]
Only some very small breaking changes: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#breaking-changes

I can back out that commit if you'd like to stick to Typescript 3

**Comment by pahen** [comment]
Yes, I think that's best.

**Comment by realityking** [comment]
@pahen Done

**Comment by pahen** [comment]
How about this one? https://github.com/pahen/detective-typescript/pull/30/commits/52b8803fcf6e94af4446fce4e8f8912858bad7a5

**Comment by realityking** [comment]
These are all the breaking changes in that package:

- Dropped support for Node version 8
- Dropped support for TypeScript 3.2
- typescript-estree now emits a TSEmptyBodyFunctionExpression when it encounters a function expression without a body. Previously this was done in parser (for legacy reasons). This change should only affect users directly consuming typescript-estree.
- When a method is marked as optional (class Foo { name?() {} }) we now mark the MethodDefinition/TSAbstractMethodDefinition as optional. Previously we marked the key of the node as optional, but this only works if the key is an Identifier, and didn't work in the case of a computed key (class Foo { ['name']?() {} }).
- Import expressions (import('foo')) now conform to the newly released ESTree spec, outputting as an ImportExpression. 
- BigInt literals now conform to the newly released ESTree spec, outputting as a Literal with a value of type bigint. (#1999)
- typescript-estree: - removes the ability to supply a RegExp to projectFolderIgnoreList, and changes the meaning of the string value from a regex to a glob.
- Removed decorators property from several Nodes that could never semantically have them (FunctionDeclaration, TSEnumDeclaration, and TSInterfaceDeclaration)
- Removed AST_NODE_TYPES.Import. This is a minor breaking change as the node type that used this was removed ages ago.

Most of them are minor AST changes. The only one affecting this module is

> Import expressions (import('foo')) now conform to the newly released ESTree spec, outputting as an ImportExpression

and I've made the necessary changes in the same PR

**Comment by pahen** [comment]
Ok, what's the reason for upgrading? Did you find any issues?

**Comment by realityking** [comment]
I'm mainly after the deduplication with other consumers of `@typescript-eslint/typescript-estree`. I have some changes to other dependencies of madge worming itself through the dependencies and I figured this would be a good opportunity to upgrade this one as well.

**Comment by pahen** [comment]
Thanks for the help! Published detective-typescript@6.0.0 to NPM now.

**Pull request merged**
