### PR TITLE
mocha: tighten options

### PR DESCRIPTION
**Pull request by XhmikosR**
Refs:

* https://github.com/dependents/node-precinct/pull/100
* https://github.com/dependents/node-source-walk/pull/28

### CODE REVIEW

**Review by mrjoelkemp — APPROVED** [review]

**Comment by mrjoelkemp** [comment]
Thanks for your tireless work @XhmikosR. 

I didn't realize I had write permission and also npm publish rights to this package. So I just took care of the merging and publishing.

**Comment by XhmikosR** [comment]
@mrjoelkemp thanks!

There's also #41 which should be a major bump. BTW have you thought about moving the repo to the dependents org?

**Comment by XhmikosR** [comment]
Cheers, thanks! Now we only need to figure out the node-source-walk strict issue and then bump the major deps in precinct itself.

**Comment by XhmikosR** [comment]
Forgot to comment on the repo move. It should definitely help for the future of the project, assuming of course you add @pahen too to the org.

**Comment by pahen** [comment]
Thanks for all the help! I'm very happy to move the repo to dependents org since I'm not a user of typescript and not a good maintainer of this project.

**Comment by XhmikosR** [comment]
@pahen I think you are the one who can move the repo to the dependents org :)

**Comment by pahen** [comment]
Yes, I tried but I'm getting "You don’t have the permission to create public repositories on dependents" when trying this.

Screenshot 2022-02-22 at 12 41 31

I suppose @mrjoelkemp must give me temporary access to be able to transfer it :)

**Comment by XhmikosR** [comment]
Can you try now please?

**Comment by pahen** [comment]
> Can you try now please?

Still same error

**Comment by XhmikosR** [comment]
I've sent you an invitation, you should first accept it and then try again :)

**Comment by pahen** [comment]
It's transfered now! :)

**Comment by pahen** [comment]
I've added you as a maintainer in https://www.npmjs.com/package/detective-typescript now too @XhmikosR

**Comment by pahen** [comment]
The package.json should be updated to reflect the transfer:

Screenshot 2022-02-22 at 12 59 47

**Comment by XhmikosR** [comment]
Thanks! I fixed the links in https://github.com/dependents/detective-typescript/commit/e943f717eda2138976c3b1c04b8669d1da361424

**Pull request merged**
